Added usage to README.md
shaharke/bootleg pull request #1
Opened 2017-07-19 15:03 UTC by peroman86

Added usage to README.md

Just added that the required module must be a function

2018-11-26 15:48 UTC, peroman86 commented
@shaharke

2018-11-26 18:45 UTC, peroman86 commented
@shaharke , don't forget me too :)

2018-11-27 08:04 UTC, shaharke requested changes

2018-11-27 08:04 UTC, shaharke commented on README.md
> +    // the module that you require need to bee wrapped with function, object module won't work.
Fix type (bee = be)

2019-01-30 19:05 UTC, shaharke commented
@peroman86 squash and you're done

2019-01-31 07:29 UTC, peroman86 commented
@shaharke , squashed

2019-01-31 07:45 UTC, shaharke approved these changes

2019-01-31 07:46 UTC, merged